services:
  coordinator:
    build: ./src/coordinator
    container_name: coordinator
    ports:
    - 5009:5001
  node1:
    build: ./src/node
    container_name: node1
    depends_on:
    - coordinator
    ports:
    - 5002:5000
    volumes:
    - ./src/shared:/app/shared
  node2:
    build: ./src/node
    container_name: node2
    depends_on:
    - coordinator
    ports:
    - 5003:5000
    volumes:
    - ./src/shared:/app/shared
  node3:
    build: ./src/node
    container_name: node3
    depends_on:
    - coordinator
    ports:
    - 5004:5000
    volumes:
    - ./src/shared:/app/shared
  node4:
    build: ./src/node
    container_name: node4
    depends_on:
    - coordinator
    ports:
    - 5005:5000
    volumes:
    - ./src/shared:/app/shared
version: '3.8'
